# ==============================================================================
# CONJOINT HTML REPORT - PAGE BUILDER
# ==============================================================================
# Assembles complete HTML document with CSS, layout, and JavaScript
# ==============================================================================

#' Build Complete Conjoint HTML Report Page
#'
#' @param html_data Transformed data from 01_data_transformer
#' @param tables List of HTML table strings from 02_table_builder
#' @param charts List of SVG chart strings from 05_chart_builder
#' @param config Configuration
#' @return Complete HTML document string
#' @keywords internal
build_conjoint_page <- function(html_data, tables, charts, config) {

  brand <- config$brand_colour %||% "#323367"
  accent <- config$accent_colour %||% "#CC9900"
  summary <- html_data$summary

  # Build components
  css <- build_conjoint_css(brand, accent)
  meta_tags <- build_conjoint_meta(summary)
  header <- build_conjoint_header(summary, brand)
  nav <- build_conjoint_nav(html_data)
  overview_panel <- build_overview_panel(html_data, tables, charts)
  utilities_panel <- build_utilities_panel(html_data, tables, charts, brand)
  diagnostics_panel <- build_diagnostics_panel(html_data, tables, charts, brand)
  lc_panel <- build_lc_panel(html_data, tables, charts, brand)
  js <- build_conjoint_js()

  # Assemble
  sprintf(
    '<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
%s
<title>%s - Conjoint Analysis Report</title>
<style>%s</style>
</head>
<body>
%s
%s
<div class="cj-panels">
%s
%s
%s
%s
</div>
<footer class="cj-footer">
<p>Generated by TURAS Analytics Platform | The Research LampPost (Pty) Ltd | %s</p>
</footer>
<script>%s</script>
</body>
</html>',
    meta_tags, summary$project_name, css, header, nav,
    overview_panel, utilities_panel, diagnostics_panel, lc_panel,
    summary$generated, js
  )
}


# ==============================================================================
# META TAGS (Report Hub Integration)
# ==============================================================================

build_conjoint_meta <- function(summary) {
  sprintf(
    '<meta name="turas-report-type" content="conjoint">
<meta name="turas-generated" content="%s">
<meta name="turas-estimation-method" content="%s">
<meta name="turas-respondents" content="%s">
<meta name="turas-attributes" content="%d">
<meta name="turas-source-filename" content="%s">',
    summary$generated,
    summary$estimation_method,
    as.character(summary$n_respondents %||% "N/A"),
    summary$n_attributes,
    summary$project_name
  )
}


# ==============================================================================
# CSS
# ==============================================================================

build_conjoint_css <- function(brand, accent) {
  css <- '
:root { --cj-brand: BRAND; --cj-accent: ACCENT; }
* { margin:0; padding:0; box-sizing:border-box; }
body { font-family:system-ui,-apple-system,"Segoe UI",sans-serif; background:#f8fafc; color:#334155; line-height:1.6; }
.cj-header { background:BRAND; color:white; padding:28px 40px; }
.cj-header h1 { font-size:22px; font-weight:600; margin-bottom:4px; }
.cj-header .cj-subtitle { font-size:13px; opacity:0.8; }
.cj-badges { display:flex; gap:10px; margin-top:12px; flex-wrap:wrap; }
.cj-badge { background:rgba(255,255,255,0.15); padding:4px 12px; border-radius:12px; font-size:11px; font-weight:500; }
.cj-nav { display:flex; gap:0; background:white; border-bottom:2px solid #e2e8f0; padding:0 40px; position:sticky; top:0; z-index:10; }
.cj-tab { padding:12px 20px; font-size:13px; font-weight:500; color:#64748b; cursor:pointer; border-bottom:3px solid transparent; transition:all 200ms; background:none; border-top:none; border-left:none; border-right:none; }
.cj-tab:hover { color:BRAND; }
.cj-tab.active { color:BRAND; border-bottom-color:BRAND; }
.cj-panels { padding:24px 40px 60px; max-width:1200px; margin:0 auto; }
.cj-panel { display:none; }
.cj-panel.active { display:block; }
.cj-card { background:white; border-radius:8px; padding:24px; margin-bottom:20px; box-shadow:0 1px 3px rgba(0,0,0,0.06); }
.cj-card h2 { font-size:16px; font-weight:600; color:#1e293b; margin-bottom:16px; }
.cj-card h3 { font-size:14px; font-weight:600; color:#334155; margin-bottom:12px; }
.cj-kpi-row { display:flex; gap:16px; margin-bottom:20px; flex-wrap:wrap; }
.cj-kpi { background:white; border-radius:8px; padding:16px 20px; min-width:140px; box-shadow:0 1px 3px rgba(0,0,0,0.06); text-align:center; }
.cj-kpi-value { font-size:24px; font-weight:700; color:BRAND; }
.cj-kpi-label { font-size:11px; color:#64748b; margin-top:4px; font-weight:400; }
.cj-table { width:100%; border-collapse:collapse; font-size:13px; }
.cj-table th { text-align:left; padding:8px 12px; border-bottom:2px solid #e2e8f0; color:#64748b; font-weight:500; font-size:11px; text-transform:uppercase; letter-spacing:0.05em; }
.cj-table td { padding:8px 12px; border-bottom:1px solid #f1f5f9; }
.cj-label-col { font-weight:400; color:#334155; }
.cj-num { font-variant-numeric:tabular-nums; text-align:right; }
.cj-positive { color:#16a34a; font-weight:500; }
.cj-negative { color:#dc2626; font-weight:500; }
.cj-baseline { color:#94a3b8; font-size:11px; font-weight:400; }
.cj-highlight-row { background:#f0fdf4; }
.cj-bar-cell { width:200px; }
.cj-bar { height:18px; background:BRAND; border-radius:4px; opacity:0.75; transition:width 200ms; }
.cj-chart-container { margin:16px 0; }
.cj-attr-nav { display:flex; gap:8px; margin-bottom:16px; flex-wrap:wrap; }
.cj-attr-btn { padding:6px 14px; font-size:12px; font-weight:500; border:1px solid #e2e8f0; border-radius:6px; background:white; color:#64748b; cursor:pointer; transition:all 200ms; }
.cj-attr-btn:hover { border-color:BRAND; color:BRAND; }
.cj-attr-btn.active { background:BRAND; color:white; border-color:BRAND; }
.cj-attr-detail { display:none; }
.cj-attr-detail.active { display:block; }
.cj-status-pass { color:#16a34a; font-weight:600; }
.cj-status-fail { color:#dc2626; font-weight:600; }
.cj-footer { text-align:center; padding:20px 40px; color:#94a3b8; font-size:11px; border-top:1px solid #e2e8f0; }
@media (max-width:768px) { .cj-header,.cj-nav,.cj-panels,.cj-footer { padding-left:16px; padding-right:16px; } .cj-kpi-row { flex-direction:column; } }
'
  css <- gsub("BRAND", brand, css, fixed = TRUE)
  css <- gsub("ACCENT", accent, css, fixed = TRUE)
  css
}


# ==============================================================================
# HEADER
# ==============================================================================

build_conjoint_header <- function(summary, brand) {

  badges <- character()
  badges <- c(badges, sprintf('<span class="cj-badge">%s</span>', toupper(summary$estimation_method)))
  if (!is.na(summary$n_respondents)) {
    badges <- c(badges, sprintf('<span class="cj-badge">n=%s</span>', format(summary$n_respondents, big.mark = ",")))
  }
  badges <- c(badges, sprintf('<span class="cj-badge">%d Attributes</span>', summary$n_attributes))
  if (!is.na(summary$converged)) {
    status <- if (summary$converged) "Converged" else "Not Converged"
    badges <- c(badges, sprintf('<span class="cj-badge">%s</span>', status))
  }

  sprintf(
    '<header class="cj-header">
<h1>%s</h1>
<div class="cj-subtitle">Conjoint Analysis Report | Generated %s</div>
<div class="cj-badges">%s</div>
</header>',
    summary$project_name, summary$generated, paste(badges, collapse = "\n")
  )
}


# ==============================================================================
# NAVIGATION
# ==============================================================================

build_conjoint_nav <- function(html_data) {

  tabs <- list(
    list(id = "overview", label = "Overview"),
    list(id = "utilities", label = "Utilities"),
    list(id = "diagnostics", label = "Diagnostics")
  )

  if (!is.null(html_data$lc_data)) {
    tabs <- c(tabs, list(list(id = "latentclass", label = "Latent Classes")))
  }

  buttons <- vapply(tabs, function(t) {
    active <- if (t$id == "overview") ' active' else ""
    sprintf('<button class="cj-tab%s" onclick="switchCjTab(\'%s\')" data-tab="%s">%s</button>',
            active, t$id, t$id, t$label)
  }, character(1))

  sprintf('<nav class="cj-nav">%s</nav>', paste(buttons, collapse = "\n"))
}


# ==============================================================================
# OVERVIEW PANEL
# ==============================================================================

build_overview_panel <- function(html_data, tables, charts) {

  summary <- html_data$summary

  # KPIs
  kpis <- sprintf(
    '<div class="cj-kpi-row">
<div class="cj-kpi"><div class="cj-kpi-value">%s</div><div class="cj-kpi-label">Respondents</div></div>
<div class="cj-kpi"><div class="cj-kpi-value">%d</div><div class="cj-kpi-label">Attributes</div></div>
<div class="cj-kpi"><div class="cj-kpi-value">%d</div><div class="cj-kpi-label">Levels</div></div>
<div class="cj-kpi"><div class="cj-kpi-value">%s</div><div class="cj-kpi-label">Method</div></div>
</div>',
    if (!is.na(summary$n_respondents)) format(summary$n_respondents, big.mark = ",") else "N/A",
    summary$n_attributes, summary$n_levels,
    toupper(substr(summary$estimation_method, 1, 6))
  )

  sprintf(
    '<div class="cj-panel active" id="panel-overview">
%s
<div class="cj-card"><h2>Attribute Importance</h2>
<div class="cj-chart-container">%s</div>
%s
</div>
</div>',
    kpis,
    charts$importance %||% "",
    tables$importance %||% ""
  )
}


# ==============================================================================
# UTILITIES PANEL
# ==============================================================================

build_utilities_panel <- function(html_data, tables, charts, brand) {

  attrs <- names(html_data$utilities_by_attr)

  # Attribute navigation buttons
  nav_buttons <- vapply(seq_along(attrs), function(i) {
    active <- if (i == 1) " active" else ""
    sprintf('<button class="cj-attr-btn%s" onclick="switchCjAttr(\'%s\')">%s</button>',
            active, attrs[i], attrs[i])
  }, character(1))

  # Attribute detail sections
  details <- vapply(seq_along(attrs), function(i) {
    active <- if (i == 1) " active" else ""
    attr_name <- attrs[i]
    chart_html <- charts$utility_charts[[attr_name]] %||% ""
    table_html <- tables$utility_tables[[attr_name]] %||% ""

    sprintf(
      '<div class="cj-attr-detail%s" id="attr-%s">
<div class="cj-chart-container">%s</div>
%s
</div>',
      active, attr_name, chart_html, table_html
    )
  }, character(1))

  sprintf(
    '<div class="cj-panel" id="panel-utilities">
<div class="cj-card">
<h2>Part-Worth Utilities by Attribute</h2>
<div class="cj-attr-nav">%s</div>
%s
</div>
</div>',
    paste(nav_buttons, collapse = "\n"),
    paste(details, collapse = "\n")
  )
}


# ==============================================================================
# DIAGNOSTICS PANEL
# ==============================================================================

build_diagnostics_panel <- function(html_data, tables, charts, brand) {

  sections <- character()

  # Model Fit
  sections <- c(sections, sprintf(
    '<div class="cj-card"><h2>Model Fit</h2>%s</div>',
    tables$model_fit %||% '<p>No model fit data available.</p>'
  ))

  # HB Convergence (if applicable)
  if (!is.null(html_data$hb_data)) {
    hb <- html_data$hb_data
    status_class <- if (isTRUE(hb$convergence$converged)) "cj-status-pass" else "cj-status-fail"
    status_text <- if (isTRUE(hb$convergence$converged)) "CONVERGED" else "NOT CONVERGED"

    convergence_html <- sprintf(
      '<div class="cj-card"><h2>HB Convergence</h2>
<p>Status: <span class="%s">%s</span></p>
<p>Iterations: %s | Burn-in: %s | Draws retained: %s</p>
%s
</div>',
      status_class, status_text,
      format(hb$iterations %||% 0, big.mark = ","),
      format(hb$burnin %||% 0, big.mark = ","),
      format(hb$n_draws %||% 0, big.mark = ","),
      tables$convergence %||% ""
    )
    sections <- c(sections, convergence_html)

    # Respondent quality
    if (!is.null(hb$quality)) {
      quality_html <- sprintf(
        '<div class="cj-card"><h2>Respondent Quality</h2>
<p>Mean RLH: <strong>%.3f</strong> | Chance: %.3f | Flagged: %d respondents</p>
</div>',
        hb$quality$mean_rlh, hb$quality$chance_rlh, hb$quality$n_flagged
      )
      sections <- c(sections, quality_html)
    }
  }

  sprintf(
    '<div class="cj-panel" id="panel-diagnostics">%s</div>',
    paste(sections, collapse = "\n")
  )
}


# ==============================================================================
# LATENT CLASS PANEL
# ==============================================================================

build_lc_panel <- function(html_data, tables, charts, brand) {

  if (is.null(html_data$lc_data)) return('<div class="cj-panel" id="panel-latentclass"></div>')

  lc <- html_data$lc_data
  sections <- character()

  # Summary
  sections <- c(sections, sprintf(
    '<div class="cj-card"><h2>Latent Class Summary</h2>
<div class="cj-kpi-row">
<div class="cj-kpi"><div class="cj-kpi-value">%d</div><div class="cj-kpi-label">Optimal Classes</div></div>
<div class="cj-kpi"><div class="cj-kpi-value">%.3f</div><div class="cj-kpi-label">Entropy R\u00b2</div></div>
</div>
</div>',
    lc$optimal_k, lc$entropy_r2
  ))

  # BIC chart + comparison table
  sections <- c(sections, sprintf(
    '<div class="cj-card"><h2>Model Comparison</h2>
<div class="cj-chart-container">%s</div>
%s
</div>',
    charts$bic %||% "",
    tables$lc_comparison %||% ""
  ))

  # Class sizes
  if (!is.null(lc$class_sizes)) {
    size_rows <- vapply(seq_along(lc$class_sizes), function(c) {
      sprintf('<tr><td>Class %d</td><td class="cj-num">%d</td><td class="cj-num">%.1f%%</td></tr>',
              c, lc$class_sizes[c], lc$class_proportions[c] * 100)
    }, character(1))

    sections <- c(sections, sprintf(
      '<div class="cj-card"><h2>Class Sizes</h2>
<table class="cj-table"><thead><tr><th>Class</th><th>Size</th><th>Percentage</th></tr></thead><tbody>%s</tbody></table>
</div>',
      paste(size_rows, collapse = "\n")
    ))
  }

  sprintf('<div class="cj-panel" id="panel-latentclass">%s</div>', paste(sections, collapse = "\n"))
}


# ==============================================================================
# JAVASCRIPT
# ==============================================================================

build_conjoint_js <- function() {
  # Read from external JS file if available, otherwise inline
  js_path <- file.path(dirname(sys.frame(1)$ofile %||% "."), "js", "conjoint_navigation.js")
  if (file.exists(js_path)) {
    return(paste(readLines(js_path, warn = FALSE), collapse = "\n"))
  }

  # Inline fallback
  '
function switchCjTab(tabName) {
  document.querySelectorAll(".cj-tab").forEach(function(t) { t.classList.remove("active"); });
  document.querySelectorAll(".cj-panel").forEach(function(p) { p.classList.remove("active"); });
  var btn = document.querySelector(".cj-tab[data-tab=\\"" + tabName + "\\"]");
  if (btn) btn.classList.add("active");
  var panel = document.getElementById("panel-" + tabName);
  if (panel) panel.classList.add("active");
}
function switchCjAttr(attrName) {
  document.querySelectorAll(".cj-attr-btn").forEach(function(b) { b.classList.remove("active"); });
  document.querySelectorAll(".cj-attr-detail").forEach(function(d) { d.classList.remove("active"); });
  event.target.classList.add("active");
  var detail = document.getElementById("attr-" + attrName);
  if (detail) detail.classList.add("active");
}
document.addEventListener("DOMContentLoaded", function() { switchCjTab("overview"); });
'
}
