# ==============================================================================
# CONJOINT HTML REPORT - PAGE BUILDER
# ==============================================================================
# Assembles the complete HTML document with CSS, layout, and JavaScript.
# Matches Turas tabs-level quality: dark gradient header, sidebar navigation,
# insight blocks, pins, exports, about page, help overlay, print CSS.
# All output is a self-contained HTML string — no htmltools dependency.
# ==============================================================================


#' Build Complete Conjoint HTML Report Page
#'
#' Main orchestrator that assembles all components into a single HTML document.
#'
#' @param html_data Transformed data from 01_data_transformer
#' @param tables List of HTML table strings from 02_table_builder
#' @param charts List of SVG chart strings from 05_chart_builder
#' @param config Configuration list
#' @return Complete HTML document string
#' @keywords internal
build_conjoint_page <- function(html_data, tables, charts, config) {

  brand <- config$brand_colour %||% "#323367"
  accent <- config$accent_colour %||% "#CC9900"
  summary <- html_data$summary

  # Build components
  meta_tags    <- build_conjoint_meta(summary, config)
  css          <- build_conjoint_css(brand, accent)
  print_css    <- build_conjoint_print_css()
  header       <- build_conjoint_header(summary, brand, config)
  nav          <- build_report_tab_nav(html_data, config)
  overview     <- build_overview_panel(html_data, tables, charts, config)
  utilities    <- build_utilities_panel(html_data, tables, charts, brand, config)
  diagnostics  <- build_diagnostics_panel(html_data, tables, charts, brand)
  lc_panel     <- build_lc_panel(html_data, tables, charts, brand)
  wtp_panel    <- build_wtp_panel(html_data, tables, charts, brand)
  simulator    <- build_simulator_panel(html_data, brand)
  about        <- build_about_panel(html_data$about, config)
  pinned       <- build_pinned_panel()
  help_overlay <- build_help_overlay()
  js           <- build_conjoint_js()

  # Simulator data JSON (embedded for JS engine)
  sim_json <- if (!is.null(html_data$simulator_data)) {
    simulator_data_to_json(html_data$simulator_data)
  } else "{}"

  sprintf(
    '<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
%s
<title>%s - Conjoint Analysis Report</title>
<style>%s</style>
<style>%s</style>
</head>
<body>
%s
%s
<div class="cj-panels-wrap">
%s
%s
%s
%s
%s
%s
%s
%s
</div>
%s
<footer class="cj-footer">
<p>Generated by TURAS Analytics Platform | The Research LampPost (Pty) Ltd | %s</p>
</footer>
<script type="application/json" id="cj-simulator-data">%s</script>
<script type="application/json" id="pinned-views-data">[]</script>
<script>%s</script>
</body>
</html>',
    meta_tags, .html_esc(summary$project_name), css, print_css,
    header, nav,
    overview, utilities, diagnostics, lc_panel, wtp_panel, simulator, about, pinned,
    help_overlay,
    summary$generated, sim_json, js
  )
}


# ==============================================================================
# META TAGS (Report Hub Integration)
# ==============================================================================

#' @keywords internal
build_conjoint_meta <- function(summary, config = list()) {
  source_file <- config$source_filename %||% summary$project_name
  sprintf(
    '<meta name="turas-report-type" content="conjoint">
<meta name="turas-generated" content="%s">
<meta name="turas-estimation-method" content="%s">
<meta name="turas-respondents" content="%s">
<meta name="turas-attributes" content="%d">
<meta name="turas-source-filename" content="%s">',
    summary$generated,
    summary$estimation_method,
    as.character(summary$n_respondents %||% "N/A"),
    summary$n_attributes,
    .html_esc(source_file)
  )
}


# ==============================================================================
# CSS
# ==============================================================================

#' @keywords internal
build_conjoint_css <- function(brand, accent) {
  css <- '
:root {
  --cj-brand: BRAND;
  --cj-accent: ACCENT;
}
* { margin:0; padding:0; box-sizing:border-box; }
body { font-family:system-ui,-apple-system,"Segoe UI",sans-serif; background:#f8fafc; color:#334155; line-height:1.6; }

/* === HEADER === */
.cj-header {
  background: linear-gradient(135deg, #1a2744, #2a3f5f);
  color: white;
  padding: 24px 40px 20px;
  border-bottom: 3px solid BRAND;
}
.cj-header-inner { display:flex; flex-direction:column; max-width:1400px; margin:0 auto; }
.cj-header-top { display:flex; align-items:center; justify-content:space-between; }
.cj-header-branding { display:flex; align-items:center; gap:16px; }
.cj-header-logo { height:56px; width:56px; object-fit:contain; border-radius:8px; }
.cj-header-titles h1 { font-size:24px; font-weight:700; letter-spacing:-0.3px; line-height:1.2; }
.cj-header-subtitle { color:rgba(255,255,255,0.5); font-size:12px; margin-top:2px; }
.cj-study-name { color:#ffffff; font-size:20px; font-weight:700; letter-spacing:-0.3px; margin-top:14px; }
.cj-prepared-by { color:rgba(255,255,255,0.65); font-size:13px; margin-top:4px; }
.cj-prepared-by strong { font-weight:600; }

/* Badge bar */
.cj-badge-bar {
  display:inline-flex; align-items:center; margin-top:12px;
  border:1px solid rgba(255,255,255,0.15); border-radius:6px;
  background:rgba(255,255,255,0.05);
}
.cj-badge-item { display:inline-flex; align-items:center; padding:4px 12px; font-size:12px; font-weight:600; color:rgba(255,255,255,0.85); }
.cj-badge-item strong { color:#fff; font-weight:700; }
.cj-badge-sep { width:1px; height:16px; background:rgba(255,255,255,0.20); flex-shrink:0; }

/* Help button */
.cj-help-btn {
  width:28px; height:28px; border-radius:50%; border:1.5px solid rgba(255,255,255,0.5);
  background:transparent; color:rgba(255,255,255,0.8); font-size:14px; font-weight:700;
  cursor:pointer; display:flex; align-items:center; justify-content:center;
}
.cj-help-btn:hover { background:rgba(255,255,255,0.1); }

/* === TAB NAVIGATION === */
.cj-report-tabs {
  display:flex; gap:0; background:white; border-bottom:2px solid #e2e8f0;
  padding:0 40px; position:sticky; top:0; z-index:100;
}
.cj-report-tab {
  padding:12px 20px; font-size:13px; font-weight:500; color:#64748b;
  cursor:pointer; border:none; border-bottom:3px solid transparent;
  background:none; transition:all 200ms;
}
.cj-report-tab:hover { color:BRAND; }
.cj-report-tab.active { color:BRAND; border-bottom-color:BRAND; }

/* === MAIN CONTENT === */
.cj-panels-wrap { max-width:1400px; margin:0 auto; padding:24px 40px 60px; }
.cj-panel { display:none; }
.cj-panel.active { display:block; }

/* === CARDS === */
.cj-card {
  background:white; border-radius:8px; padding:24px; margin-bottom:20px;
  box-shadow:0 1px 3px rgba(0,0,0,0.06);
}
.cj-card h2 { font-size:16px; font-weight:600; color:#1e293b; margin-bottom:16px; }
.cj-card h3 { font-size:14px; font-weight:600; color:#334155; margin-bottom:12px; }

/* === KPI ROW === */
.cj-kpi-row { display:flex; gap:16px; margin-bottom:20px; flex-wrap:wrap; }
.cj-kpi {
  background:white; border-radius:8px; padding:16px 20px; min-width:140px;
  box-shadow:0 1px 3px rgba(0,0,0,0.06); text-align:center; flex:1;
}
.cj-kpi-value { font-size:24px; font-weight:700; color:BRAND; }
.cj-kpi-label { font-size:11px; color:#64748b; margin-top:4px; }

/* === UTILITIES SIDEBAR LAYOUT === */
.cj-util-layout { display:flex; gap:24px; }
.cj-util-sidebar {
  width:260px; flex-shrink:0; position:sticky; top:60px; align-self:flex-start;
  max-height:calc(100vh - 80px); overflow-y:auto;
  background:white; border-radius:8px; box-shadow:0 1px 3px rgba(0,0,0,0.06); padding:16px;
}
.cj-util-sidebar-header { font-size:12px; font-weight:600; color:#64748b; text-transform:uppercase; letter-spacing:0.05em; margin-bottom:12px; }
.cj-util-search {
  width:100%; padding:8px 12px; border:1px solid #e2e8f0; border-radius:6px;
  font-size:12px; margin-bottom:12px; outline:none;
}
.cj-util-search:focus { border-color:BRAND; }
.cj-util-item {
  padding:8px 12px; border-radius:6px; cursor:pointer; font-size:13px;
  color:#334155; transition:all 150ms; margin-bottom:2px;
}
.cj-util-item:hover { background:#f1f5f9; }
.cj-util-item.active { background:BRAND; color:white; font-weight:500; }
.cj-util-item-count { font-size:11px; color:#94a3b8; float:right; }
.cj-util-item.active .cj-util-item-count { color:rgba(255,255,255,0.7); }
.cj-util-content { flex:1; min-width:0; }
.cj-attr-detail { display:none; }
.cj-attr-detail.active { display:block; }

/* === TABLES === */
.cj-table { width:100%; border-collapse:collapse; font-size:13px; }
.cj-table th { text-align:left; padding:8px 12px; border-bottom:2px solid #e2e8f0; color:#64748b; font-weight:500; font-size:11px; text-transform:uppercase; letter-spacing:0.05em; }
.cj-table td { padding:8px 12px; border-bottom:1px solid #f1f5f9; }
.cj-label-col { font-weight:400; color:#334155; }
.cj-num { font-variant-numeric:tabular-nums; text-align:right; }
.cj-positive { color:#16a34a; font-weight:500; }
.cj-negative { color:#dc2626; font-weight:500; }
.cj-baseline { color:#94a3b8; font-size:11px; font-weight:400; }
.cj-highlight-row { background:#f0fdf4; }
.cj-bar-cell { width:200px; }
.cj-bar { height:18px; background:BRAND; border-radius:4px; opacity:0.75; transition:width 200ms; }

/* === CHART CONTAINERS === */
.cj-chart-container { margin:16px 0; }
.cj-chart-wrap { margin:8px 0; }

/* === EXPORT BUTTONS === */
.cj-export-bar { display:flex; gap:8px; margin-bottom:16px; flex-wrap:wrap; }
.cj-export-btn {
  display:inline-flex; align-items:center; gap:4px; padding:6px 12px;
  font-size:11px; font-weight:500; border:1px solid #e2e8f0; border-radius:6px;
  background:white; color:#64748b; cursor:pointer; transition:all 200ms;
}
.cj-export-btn:hover { border-color:BRAND; color:BRAND; }

/* === INSIGHT AREAS === */
.cj-insight-area { margin-top:16px; border-top:1px solid #f1f5f9; padding-top:12px; }
.cj-insight-toggle {
  font-size:12px; color:BRAND; cursor:pointer; font-weight:500;
  background:none; border:none; padding:4px 0;
}
.cj-insight-toggle:hover { text-decoration:underline; }
.cj-insight-body { display:none; margin-top:8px; }
.cj-insight-body.open { display:block; }
.cj-insight-editor {
  min-height:60px; padding:12px; border:1px solid #e2e8f0; border-radius:6px;
  font-size:13px; line-height:1.5; color:#334155; outline:none;
}
.cj-insight-editor:focus { border-color:BRAND; box-shadow:0 0 0 2px rgba(50,51,103,0.1); }
.cj-insight-editor:empty::before {
  content:attr(data-placeholder); color:#94a3b8; font-style:italic;
}

/* === PIN BUTTON === */
.cj-pin-btn {
  display:inline-flex; align-items:center; gap:4px; padding:4px 10px;
  font-size:11px; font-weight:500; border:1px solid #e2e8f0; border-radius:6px;
  background:white; color:#94a3b8; cursor:pointer; transition:all 200ms;
}
.cj-pin-btn:hover { border-color:BRAND; color:BRAND; }
.cj-pin-btn.pinned { background:BRAND; color:white; border-color:BRAND; }

/* === PINNED VIEWS === */
.cj-pinned-container { min-height:200px; }
.cj-pinned-header { display:flex; align-items:center; justify-content:space-between; margin-bottom:20px; }
.cj-pinned-empty {
  text-align:center; padding:60px 20px; color:#94a3b8;
}
.cj-pinned-empty-icon { font-size:36px; margin-bottom:12px; }
.cj-pinned-card {
  background:white; border-radius:8px; padding:20px; margin-bottom:16px;
  box-shadow:0 1px 3px rgba(0,0,0,0.06); position:relative;
}
.cj-pinned-card-title { font-size:14px; font-weight:600; color:#1e293b; margin-bottom:8px; }
.cj-pinned-card-actions { position:absolute; top:12px; right:12px; display:flex; gap:6px; }
.cj-section-divider {
  border:none; border-top:2px solid #e2e8f0; margin:24px 0;
  position:relative; padding-top:8px;
}
.cj-section-title {
  font-size:14px; font-weight:600; color:#334155;
  padding:4px 12px; outline:none;
}
.cj-section-title:empty::before { content:"Section title..."; color:#94a3b8; font-style:italic; }

/* === SIMULATOR === */
.cj-sim-layout { display:flex; gap:24px; flex-wrap:wrap; }
.cj-sim-config { flex:1; min-width:300px; }
.cj-sim-results { flex:1; min-width:300px; }
.cj-sim-product {
  background:white; border-radius:8px; padding:16px; margin-bottom:12px;
  box-shadow:0 1px 3px rgba(0,0,0,0.06); border-left:3px solid BRAND;
}
.cj-sim-product h4 { font-size:13px; font-weight:600; color:#1e293b; margin-bottom:8px; }
.cj-sim-select {
  width:100%; padding:6px 10px; border:1px solid #e2e8f0; border-radius:4px;
  font-size:12px; margin-bottom:6px; outline:none;
}
.cj-sim-select:focus { border-color:BRAND; }
.cj-sim-add-btn {
  display:inline-flex; align-items:center; gap:4px; padding:8px 16px;
  font-size:12px; font-weight:500; border:1px solid #e2e8f0; border-radius:6px;
  background:white; color:BRAND; cursor:pointer;
}
.cj-sim-add-btn:hover { background:BRAND; color:white; }
.cj-sim-share-bar { margin:8px 0; }
.cj-sim-bar-bg { height:28px; background:#f1f5f9; border-radius:4px; overflow:hidden; position:relative; }
.cj-sim-bar-fill { height:100%; border-radius:4px; transition:width 300ms; display:flex; align-items:center; justify-content:flex-end; padding-right:8px; color:white; font-size:11px; font-weight:600; }
.cj-sim-mode-btns { display:flex; gap:8px; margin-bottom:16px; }
.cj-sim-mode-btn {
  padding:6px 14px; font-size:12px; font-weight:500; border:1px solid #e2e8f0;
  border-radius:6px; background:white; color:#64748b; cursor:pointer;
}
.cj-sim-mode-btn.active { background:BRAND; color:white; border-color:BRAND; }

/* === ABOUT PAGE === */
.cj-about-section { max-width:700px; }
.cj-about-grid { display:grid; grid-template-columns:120px 1fr; gap:8px 16px; margin-bottom:16px; }
.cj-about-label { font-size:12px; font-weight:500; color:#64748b; text-transform:uppercase; letter-spacing:0.05em; }
.cj-about-value { font-size:13px; color:#334155; }
.cj-about-value a { color:BRAND; text-decoration:none; }
.cj-about-value a:hover { text-decoration:underline; }
.cj-about-notes {
  min-height:80px; padding:12px; border:1px solid #e2e8f0; border-radius:6px;
  font-size:13px; line-height:1.5; outline:none; margin-top:8px;
}
.cj-about-notes:focus { border-color:BRAND; }
.cj-about-notes:empty::before { content:attr(data-placeholder); color:#94a3b8; font-style:italic; }

/* === HELP OVERLAY === */
.cj-help-overlay {
  display:none; position:fixed; inset:0; background:rgba(0,0,0,0.5);
  z-index:1000; align-items:center; justify-content:center;
}
.cj-help-overlay.open { display:flex; }
.cj-help-card {
  background:white; border-radius:12px; padding:32px; max-width:500px; width:90%;
  box-shadow:0 20px 60px rgba(0,0,0,0.2);
}
.cj-help-card h2 { font-size:18px; font-weight:700; color:#1e293b; margin-bottom:16px; }
.cj-help-card ul { list-style:none; padding:0; }
.cj-help-card li { padding:6px 0; font-size:13px; color:#334155; display:flex; gap:8px; }
.cj-help-key { font-weight:600; color:BRAND; min-width:120px; flex-shrink:0; }
.cj-help-dismiss { text-align:center; margin-top:20px; font-size:12px; color:#94a3b8; }

/* === STATUS INDICATORS === */
.cj-status-pass { color:#16a34a; font-weight:600; }
.cj-status-fail { color:#dc2626; font-weight:600; }

/* === FOOTER === */
.cj-footer { text-align:center; padding:20px 40px; color:#94a3b8; font-size:11px; border-top:1px solid #e2e8f0; }

/* === RESPONSIVE === */
@media (max-width:768px) {
  .cj-header, .cj-report-tabs, .cj-panels-wrap, .cj-footer { padding-left:16px; padding-right:16px; }
  .cj-kpi-row { flex-direction:column; }
  .cj-util-layout { flex-direction:column; }
  .cj-util-sidebar { width:100%; position:static; max-height:none; }
  .cj-sim-layout { flex-direction:column; }
}
'
  css <- gsub("BRAND", brand, css, fixed = TRUE)
  css <- gsub("ACCENT", accent, css, fixed = TRUE)
  css
}


# ==============================================================================
# PRINT CSS
# ==============================================================================

#' @keywords internal
build_conjoint_print_css <- function() {
  '
@page { size: A4 landscape; margin: 10mm 12mm; }
@media print {
  .cj-report-tabs, .cj-export-bar, .cj-export-btn, .cj-pin-btn,
  .cj-insight-toggle, .cj-help-overlay, .cj-help-btn,
  .cj-util-search, .cj-sim-add-btn, .cj-sim-mode-btns,
  .cj-pinned-card-actions, #panel-pinned, #panel-simulator { display:none !important; }

  body { background:white !important; font-size:14px; -webkit-print-color-adjust:exact; print-color-adjust:exact; }
  .cj-panels-wrap { padding:0 !important; max-width:none !important; }
  .cj-panel { display:block !important; page-break-inside:avoid; margin-bottom:16px; }
  .cj-card { box-shadow:none !important; border:1px solid #e2e8f0; page-break-inside:avoid; }

  .cj-header {
    padding:8px 0 6px 0 !important; background:none !important;
    border-bottom:2px solid #1a2744 !important;
  }
  .cj-header-inner * { color:#1a2744 !important; }
  .cj-badge-bar { border-color:#ccc !important; }
  .cj-badge-item { color:#334155 !important; }

  .cj-util-layout { display:block !important; }
  .cj-util-sidebar { display:none !important; }
  .cj-attr-detail { display:block !important; page-break-inside:avoid; }

  .cj-insight-body { display:block !important; }
  .cj-insight-editor:empty { display:none !important; }

  .cj-footer { font-size:9px !important; padding:4px 0 !important; border-top:1px solid #ccc; }
}
'
}


# ==============================================================================
# HEADER
# ==============================================================================

#' @keywords internal
build_conjoint_header <- function(summary, brand, config = list()) {

  # Logo
  logo_html <- ""
  logo_uri <- config$researcher_logo_base64 %||% config$researcher_logo_uri %||% NULL
  if (!is.null(logo_uri) && nzchar(logo_uri)) {
    logo_html <- sprintf(
      '<div style="width:72px;height:72px;border-radius:12px;display:flex;align-items:center;justify-content:center;flex-shrink:0;"><img src="%s" alt="Logo" class="cj-header-logo"/></div>',
      logo_uri
    )
  }

  # Help button
  help_btn <- '<button class="cj-help-btn" onclick="toggleHelpOverlay()" title="Show help guide">?</button>'

  # Prepared by line
  prepared_parts <- character()
  company <- config$company_name %||% "The Research LampPost"
  if (nzchar(company)) prepared_parts <- c(prepared_parts, sprintf("Prepared by <strong>%s</strong>", .html_esc(company)))
  client <- config$client_name %||% ""
  if (nzchar(client)) prepared_parts <- c(prepared_parts, sprintf("for <strong>%s</strong>", .html_esc(client)))
  prepared_html <- if (length(prepared_parts) > 0) {
    sprintf('<div class="cj-prepared-by">%s</div>', paste(prepared_parts, collapse = " "))
  } else ""

  # Badges
  badges <- character()
  badges <- c(badges, sprintf('<span class="cj-badge-item">%s</span>', toupper(summary$estimation_method)))
  if (!is.na(summary$n_respondents)) {
    badges <- c(badges, sprintf('<span class="cj-badge-item">n&nbsp;=&nbsp;<strong>%s</strong></span>',
                                format(summary$n_respondents, big.mark = ",")))
  }
  badges <- c(badges, sprintf('<span class="cj-badge-item"><strong>%d</strong>&nbsp;Attributes</span>', summary$n_attributes))
  if (!is.na(summary$converged)) {
    status <- if (summary$converged) "Converged" else "Not Converged"
    badges <- c(badges, sprintf('<span class="cj-badge-item">%s</span>', status))
  }
  badges <- c(badges, sprintf('<span class="cj-badge-item" id="cj-header-date">Created %s</span>',
                               format(Sys.Date(), "%b %Y")))

  badge_html <- paste(badges, collapse = '<span class="cj-badge-sep"></span>')

  sprintf(
    '<header class="cj-header">
<div class="cj-header-inner">
<div class="cj-header-top">
<div class="cj-header-branding">%s
<div class="cj-header-titles">
<h1>Turas Conjoint</h1>
<div class="cj-header-subtitle">Interactive Conjoint Analysis Report</div>
</div>
</div>
%s
</div>
<div class="cj-study-name">%s</div>
%s
<div class="cj-badge-bar">%s</div>
</div>
</header>',
    logo_html, help_btn,
    .html_esc(summary$project_name), prepared_html, badge_html
  )
}


# ==============================================================================
# TAB NAVIGATION
# ==============================================================================

#' @keywords internal
build_report_tab_nav <- function(html_data, config = list()) {

  tabs <- list(
    list(id = "overview",    label = "Overview"),
    list(id = "utilities",   label = "Utilities"),
    list(id = "diagnostics", label = "Diagnostics")
  )

  if (!is.null(html_data$lc_data)) {
    tabs <- c(tabs, list(list(id = "latentclass", label = "Latent Classes")))
  }
  if (!is.null(html_data$wtp_data)) {
    tabs <- c(tabs, list(list(id = "wtp", label = "WTP")))
  }
  tabs <- c(tabs, list(list(id = "simulator", label = "Simulator")))

  # About tab (conditional)
  has_about <- !is.null(html_data$about) && isTRUE(html_data$about$has_content)
  if (has_about) {
    tabs <- c(tabs, list(list(id = "about", label = "About")))
  }

  tabs <- c(tabs, list(list(id = "pinned", label = "Pinned")))

  buttons <- vapply(tabs, function(t) {
    active <- if (t$id == "overview") " active" else ""
    sprintf(
      '<button class="cj-report-tab%s" onclick="switchReportTab(\'%s\')" data-tab="%s">%s</button>',
      active, t$id, t$id, t$label
    )
  }, character(1))

  sprintf('<nav class="cj-report-tabs">%s</nav>', paste(buttons, collapse = "\n"))
}


# ==============================================================================
# OVERVIEW PANEL
# ==============================================================================

#' @keywords internal
build_overview_panel <- function(html_data, tables, charts, config = list()) {

  summary <- html_data$summary

  kpis <- sprintf(
    '<div class="cj-kpi-row">
<div class="cj-kpi"><div class="cj-kpi-value">%s</div><div class="cj-kpi-label">Respondents</div></div>
<div class="cj-kpi"><div class="cj-kpi-value">%d</div><div class="cj-kpi-label">Attributes</div></div>
<div class="cj-kpi"><div class="cj-kpi-value">%d</div><div class="cj-kpi-label">Levels</div></div>
<div class="cj-kpi"><div class="cj-kpi-value">%s</div><div class="cj-kpi-label">Method</div></div>
<div class="cj-kpi"><div class="cj-kpi-value">%s</div><div class="cj-kpi-label">Choice Sets</div></div>
</div>',
    if (!is.na(summary$n_respondents)) format(summary$n_respondents, big.mark = ",") else "N/A",
    summary$n_attributes, summary$n_levels,
    toupper(substr(summary$estimation_method, 1, 8)),
    if (!is.na(summary$n_choice_sets)) format(summary$n_choice_sets, big.mark = ",") else "N/A"
  )

  export_bar <- .build_export_bar("overview")
  insight <- build_insight_area("overview", html_data$insights)

  sprintf(
    '<div class="cj-panel active" id="panel-overview">
%s
<div class="cj-card">
%s
<h2>Attribute Importance</h2>
<div class="cj-chart-container">%s</div>
%s
%s
</div>
</div>',
    kpis, export_bar,
    charts$importance %||% "",
    tables$importance %||% "",
    insight
  )
}


# ==============================================================================
# UTILITIES PANEL (with sidebar)
# ==============================================================================

#' @keywords internal
build_utilities_panel <- function(html_data, tables, charts, brand, config = list()) {

  attrs <- names(html_data$utilities_by_attr)
  if (length(attrs) == 0) {
    return('<div class="cj-panel" id="panel-utilities"><div class="cj-card"><p>No utilities data available.</p></div></div>')
  }

  # Sidebar items
  sidebar_items <- vapply(seq_along(attrs), function(i) {
    active <- if (i == 1) " active" else ""
    n_levels <- nrow(html_data$utilities_by_attr[[attrs[i]]])
    sprintf(
      '<div class="cj-util-item%s" data-attr="%s" onclick="selectAttribute(\'%s\')">%s<span class="cj-util-item-count">%d levels</span></div>',
      active, .html_esc(attrs[i]), .html_esc(attrs[i]), .html_esc(attrs[i]), n_levels
    )
  }, character(1))

  sidebar <- sprintf(
    '<div class="cj-util-sidebar">
<div class="cj-util-sidebar-header">Attributes (%d)</div>
<input type="text" class="cj-util-search" placeholder="Search attributes..." oninput="filterAttributes(this.value)">
%s
</div>',
    length(attrs), paste(sidebar_items, collapse = "\n")
  )

  # Detail sections per attribute
  details <- vapply(seq_along(attrs), function(i) {
    active <- if (i == 1) " active" else ""
    attr_name <- attrs[i]
    chart_html <- charts$utility_charts[[attr_name]] %||% ""
    table_html <- tables$utility_tables[[attr_name]] %||% ""
    export_bar <- .build_export_bar(paste0("util-", gsub("[^a-zA-Z0-9]", "-", attr_name)))
    pin_btn <- sprintf(
      '<button class="cj-pin-btn" onclick="togglePin(\'util-%s\')">Pin</button>',
      .html_esc(attr_name)
    )

    sprintf(
      '<div class="cj-attr-detail%s" data-attr="%s">
<div class="cj-card">
<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:12px;">
<h2 style="margin-bottom:0;">%s</h2>
<div style="display:flex;gap:8px;">%s %s</div>
</div>
<div class="cj-chart-container">%s</div>
%s
</div>
</div>',
      active, .html_esc(attr_name), .html_esc(attr_name),
      pin_btn, export_bar, chart_html, table_html
    )
  }, character(1))

  insight <- build_insight_area("utilities", html_data$insights)

  sprintf(
    '<div class="cj-panel" id="panel-utilities">
<div class="cj-util-layout">
%s
<div class="cj-util-content">
%s
%s
</div>
</div>
</div>',
    sidebar, paste(details, collapse = "\n"), insight
  )
}


# ==============================================================================
# DIAGNOSTICS PANEL
# ==============================================================================

#' @keywords internal
build_diagnostics_panel <- function(html_data, tables, charts, brand) {

  sections <- character()
  export_bar <- .build_export_bar("diagnostics")

  # Model Fit
  sections <- c(sections, sprintf(
    '<div class="cj-card">%s<h2>Model Fit</h2>%s</div>',
    export_bar,
    tables$model_fit %||% '<p>No model fit data available.</p>'
  ))

  # HB Convergence
  if (!is.null(html_data$hb_data)) {
    hb <- html_data$hb_data
    status_class <- if (isTRUE(hb$convergence$converged)) "cj-status-pass" else "cj-status-fail"
    status_text <- if (isTRUE(hb$convergence$converged)) "CONVERGED" else "NOT CONVERGED"

    sections <- c(sections, sprintf(
      '<div class="cj-card"><h2>HB Convergence</h2>
<p>Status: <span class="%s">%s</span></p>
<p>Iterations: %s | Burn-in: %s | Draws retained: %s</p>
%s
</div>',
      status_class, status_text,
      format(hb$iterations %||% 0, big.mark = ","),
      format(hb$burnin %||% 0, big.mark = ","),
      format(hb$n_draws %||% 0, big.mark = ","),
      tables$convergence %||% ""
    ))

    # Respondent quality
    if (!is.null(hb$quality)) {
      sections <- c(sections, sprintf(
        '<div class="cj-card"><h2>Respondent Quality</h2>%s</div>',
        tables$respondent_quality %||% sprintf(
          '<p>Mean RLH: <strong>%.3f</strong> | Chance: %.3f | Flagged: %d</p>',
          hb$quality$mean_rlh, hb$quality$chance_rlh, hb$quality$n_flagged
        )
      ))
    }
  }

  insight <- build_insight_area("diagnostics", html_data$insights)

  sprintf(
    '<div class="cj-panel" id="panel-diagnostics">%s%s</div>',
    paste(sections, collapse = "\n"), insight
  )
}


# ==============================================================================
# LATENT CLASS PANEL
# ==============================================================================

#' @keywords internal
build_lc_panel <- function(html_data, tables, charts, brand) {

  if (is.null(html_data$lc_data)) return('<div class="cj-panel" id="panel-latentclass"></div>')

  lc <- html_data$lc_data
  sections <- character()

  # Summary KPIs
  sections <- c(sections, sprintf(
    '<div class="cj-card"><h2>Latent Class Summary</h2>
<div class="cj-kpi-row">
<div class="cj-kpi"><div class="cj-kpi-value">%d</div><div class="cj-kpi-label">Optimal Classes</div></div>
<div class="cj-kpi"><div class="cj-kpi-value">%.3f</div><div class="cj-kpi-label">Entropy R\u00b2</div></div>
</div>
</div>',
    lc$optimal_k, lc$entropy_r2
  ))

  # BIC chart + comparison table
  sections <- c(sections, sprintf(
    '<div class="cj-card"><h2>Model Comparison</h2>
<div class="cj-chart-container">%s</div>
%s
</div>',
    charts$bic %||% "",
    tables$lc_comparison %||% ""
  ))

  # Class sizes
  if (!is.null(charts$class_sizes)) {
    sections <- c(sections, sprintf(
      '<div class="cj-card"><h2>Class Sizes</h2>
<div class="cj-chart-container">%s</div>
</div>',
      charts$class_sizes
    ))
  }

  # Class importance comparison
  if (!is.null(charts$class_importance)) {
    sections <- c(sections, sprintf(
      '<div class="cj-card"><h2>Importance by Class</h2>
<div class="cj-chart-container">%s</div>
%s
</div>',
      charts$class_importance,
      tables$class_importance %||% ""
    ))
  }

  sprintf('<div class="cj-panel" id="panel-latentclass">%s</div>', paste(sections, collapse = "\n"))
}


# ==============================================================================
# WTP PANEL
# ==============================================================================

#' @keywords internal
build_wtp_panel <- function(html_data, tables, charts, brand) {

  if (is.null(html_data$wtp_data)) return('<div class="cj-panel" id="panel-wtp"></div>')

  sections <- character()
  export_bar <- .build_export_bar("wtp")

  # Price coefficient info
  price_coef <- html_data$wtp_data$price_coefficient
  price_attr <- html_data$wtp_data$price_attribute %||% "Price"
  info_html <- if (!is.na(price_coef)) {
    sprintf('<p style="font-size:12px;color:#64748b;margin-bottom:12px;">Price attribute: <strong>%s</strong> | Price coefficient: <strong>%.4f</strong></p>',
            .html_esc(price_attr), price_coef)
  } else ""

  # WTP chart + table
  sections <- c(sections, sprintf(
    '<div class="cj-card">%s<h2>Willingness to Pay</h2>
%s
<div class="cj-chart-container">%s</div>
%s
</div>',
    export_bar, info_html,
    charts$wtp %||% "",
    tables$wtp %||% ""
  ))

  # Demand curve
  if (!is.null(charts$demand_curve) || !is.null(tables$demand_curve)) {
    sections <- c(sections, sprintf(
      '<div class="cj-card"><h2>Demand Curve</h2>
<div class="cj-chart-container">%s</div>
%s
</div>',
      charts$demand_curve %||% "",
      tables$demand_curve %||% ""
    ))
  }

  insight <- build_insight_area("wtp", html_data$insights)

  sprintf('<div class="cj-panel" id="panel-wtp">%s%s</div>',
          paste(sections, collapse = "\n"), insight)
}


# ==============================================================================
# SIMULATOR PANEL
# ==============================================================================

#' @keywords internal
build_simulator_panel <- function(html_data, brand) {

  if (is.null(html_data$simulator_data)) {
    return('<div class="cj-panel" id="panel-simulator"><div class="cj-card"><p>No simulator data available.</p></div></div>')
  }

  insight <- build_insight_area("simulator", html_data$insights)

  sprintf(
    '<div class="cj-panel" id="panel-simulator">
<div class="cj-card">
<h2>Market Simulator</h2>
<p style="font-size:12px;color:#64748b;margin-bottom:16px;">Configure product profiles and compare predicted market shares.</p>
<div class="cj-sim-mode-btns">
<button class="cj-sim-mode-btn active" onclick="switchSimMode(\'shares\')">Market Shares</button>
<button class="cj-sim-mode-btn" onclick="switchSimMode(\'sensitivity\')">Sensitivity</button>
<button class="cj-sim-mode-btn" onclick="switchSimMode(\'sov\')">Source of Volume</button>
</div>
<div class="cj-sim-layout">
<div class="cj-sim-config" id="cj-sim-products">
<button class="cj-sim-add-btn" onclick="SimUI.addProduct()">+ Add Product</button>
</div>
<div class="cj-sim-results" id="cj-sim-results">
<div style="text-align:center;padding:40px;color:#94a3b8;">
<div style="font-size:24px;">Add products to see predicted shares</div>
</div>
</div>
</div>
</div>
%s
</div>',
    insight
  )
}


# ==============================================================================
# ABOUT PANEL
# ==============================================================================

#' @keywords internal
build_about_panel <- function(about, config = list()) {

  if (is.null(about) || !isTRUE(about$has_content)) {
    return('<div class="cj-panel" id="panel-about"></div>')
  }

  # Contact grid
  contact_rows <- character()
  fields <- list(
    list(key = "analyst_name",  label = "Analyst"),
    list(key = "analyst_email", label = "Email"),
    list(key = "analyst_phone", label = "Phone"),
    list(key = "client_name",   label = "Client"),
    list(key = "company_name",  label = "Company")
  )
  for (f in fields) {
    val <- about[[f$key]]
    if (!is.null(val) && nzchar(val)) {
      val_html <- if (f$key == "analyst_email") {
        sprintf('<a href="mailto:%s">%s</a>', .html_esc(val), .html_esc(val))
      } else .html_esc(val)
      contact_rows <- c(contact_rows, sprintf(
        '<div class="cj-about-label">%s</div><div class="cj-about-value">%s</div>',
        f$label, val_html
      ))
    }
  }
  contact_html <- if (length(contact_rows) > 0) {
    sprintf('<div class="cj-about-grid">%s</div>', paste(contact_rows, collapse = "\n"))
  } else ""

  # Closing notes (editable)
  notes_content <- about$closing_notes %||% ""
  notes_html <- sprintf(
    '<div class="cj-about-label" style="margin-top:16px;">Notes</div>
<div class="cj-about-notes" contenteditable="true" data-placeholder="Add closing notes..." id="cj-about-notes" oninput="syncAboutNotes()">%s</div>
<textarea style="display:none;" id="cj-about-notes-store">%s</textarea>',
    .html_esc(notes_content), .html_esc(notes_content)
  )

  sprintf(
    '<div class="cj-panel" id="panel-about">
<div class="cj-card">
<h2>About This Report</h2>
<div class="cj-about-section">
%s
%s
</div>
</div>
</div>',
    contact_html, notes_html
  )
}


# ==============================================================================
# PINNED PANEL
# ==============================================================================

#' @keywords internal
build_pinned_panel <- function() {
  '
<div class="cj-panel" id="panel-pinned">
<div class="cj-pinned-container">
<div class="cj-pinned-header">
<div>
<h2 style="font-size:18px;font-weight:700;color:#1e293b;margin-bottom:4px;">Pinned Views</h2>
<p style="font-size:12px;color:#64748b;">Pin charts and tables from other tabs to create a curated set of key findings.</p>
</div>
<div style="display:flex;gap:8px;">
<button class="cj-export-btn" onclick="addSection()">+ Add Section</button>
<button class="cj-export-btn" onclick="exportAllPinnedSlides()">Export All Slides</button>
<button class="cj-export-btn" onclick="printPinnedViews()">Print / Save PDF</button>
<button class="cj-export-btn" onclick="saveReportHTML()">Save Report</button>
</div>
</div>
<div id="cj-pinned-cards"></div>
<div class="cj-pinned-empty" id="cj-pinned-empty">
<div class="cj-pinned-empty-icon">&#128204;</div>
<div style="font-size:14px;font-weight:600;">No pinned views yet</div>
<div style="font-size:12px;margin-top:4px;">Click the Pin button on any chart or table to add it here.</div>
</div>
</div>
</div>'
}


# ==============================================================================
# HELP OVERLAY
# ==============================================================================

#' @keywords internal
build_help_overlay <- function() {
  '
<div class="cj-help-overlay" id="cj-help-overlay" onclick="toggleHelpOverlay()">
<div class="cj-help-card" onclick="event.stopPropagation()">
<h2>Quick Guide</h2>
<ul>
<li><span class="cj-help-key">Tab navigation</span>Switch between report sections</li>
<li><span class="cj-help-key">Attribute sidebar</span>Browse utilities by attribute</li>
<li><span class="cj-help-key">Search</span>Filter attributes in the sidebar</li>
<li><span class="cj-help-key">Simulator</span>Configure products and compare market shares</li>
<li><span class="cj-help-key">Sensitivity</span>Sweep an attribute to see share impact</li>
<li><span class="cj-help-key">Pin</span>Save charts/tables to the Pinned tab</li>
<li><span class="cj-help-key">+ Add Insight</span>Add analyst notes to any section</li>
<li><span class="cj-help-key">Save Report</span>Download HTML with insights embedded</li>
<li><span class="cj-help-key">Export</span>Download CSV, Excel, chart PNG, or slide PNG</li>
</ul>
<div class="cj-help-dismiss">Click anywhere to close</div>
</div>
</div>'
}


# ==============================================================================
# INSIGHT AREA (reusable)
# ==============================================================================

#' @keywords internal
build_insight_area <- function(tab_id, insights = list()) {

  seed <- insights[[tab_id]] %||% ""

  sprintf(
    '<div class="cj-insight-area" id="insight-area-%s">
<button class="cj-insight-toggle" onclick="toggleInsight(\'%s\')">+ Add Insight</button>
<div class="cj-insight-body" id="insight-body-%s"%s>
<div class="cj-insight-editor" contenteditable="true" data-placeholder="Add your analysis notes here..." id="insight-editor-%s" oninput="syncInsight(\'%s\')">%s</div>
<textarea style="display:none;" class="cj-insight-store" id="insight-store-%s">%s</textarea>
</div>
</div>',
    tab_id, tab_id, tab_id,
    if (nzchar(seed)) ' class="open"' else "",
    tab_id, tab_id, .html_esc(seed),
    tab_id, .html_esc(seed)
  )
}


# ==============================================================================
# EXPORT BAR (reusable)
# ==============================================================================

#' @keywords internal
.build_export_bar <- function(panel_id) {
  sprintf(
    '<div class="cj-export-bar">
<button class="cj-export-btn" onclick="exportCSV(\'%s\')">CSV</button>
<button class="cj-export-btn" onclick="exportExcel(\'%s\')">Excel</button>
<button class="cj-export-btn" onclick="exportChartPNG(\'%s\')">Chart PNG</button>
<button class="cj-export-btn" onclick="exportSlidePNG(\'%s\')">Slide PNG</button>
</div>',
    panel_id, panel_id, panel_id, panel_id
  )
}


# ==============================================================================
# JAVASCRIPT LOADING
# ==============================================================================

#' Concatenate all JS files inline
#' @keywords internal
build_conjoint_js <- function() {
  js_files <- c(
    "conjoint_navigation.js",
    "simulator_engine.js",
    "simulator_ui.js",
    "simulator_charts.js",
    "conjoint_export.js",
    "conjoint_pins.js",
    "conjoint_charts.js"
  )

  js_dir <- .get_conjoint_js_dir()

  js_parts <- vapply(js_files, function(f) {
    path <- file.path(js_dir, f)
    if (file.exists(path)) {
      paste(readLines(path, warn = FALSE), collapse = "\n")
    } else {
      sprintf("/* %s not found in %s */", f, js_dir)
    }
  }, character(1))

  paste(js_parts, collapse = "\n\n")
}


#' Resolve JS directory path
#' @keywords internal
.get_conjoint_js_dir <- function() {
  # Preferred: use the global set by 99_html_report_main.R
  if (exists(".conjoint_lib_dir", envir = globalenv())) {
    return(file.path(get(".conjoint_lib_dir", envir = globalenv()), "html_report", "js"))
  }
  # Fallback: sys.frame(1)$ofile (fragile)
  ofile <- tryCatch(sys.frame(1)$ofile, error = function(e) NULL)
  if (!is.null(ofile) && nzchar(ofile %||% "")) {
    return(file.path(dirname(ofile), "js"))
  }
  # Last resort
  warning("Cannot determine JS directory: set .conjoint_lib_dir before sourcing.")
  file.path(".", "js")
}


# ==============================================================================
# UTILITY
# ==============================================================================

#' HTML-escape a string
#' @keywords internal
.html_esc <- function(x) {
  if (is.null(x) || length(x) == 0) return("")
  x <- as.character(x)
  x <- gsub("&", "&amp;", x, fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  x <- gsub(">", "&gt;", x, fixed = TRUE)
  x <- gsub("\"", "&quot;", x, fixed = TRUE)
  x
}
