# ==============================================================================
# CONJOINT HTML SIMULATOR - DEPRECATED WRAPPER
# ==============================================================================
#
# Module: Conjoint Analysis - HTML Simulator Generator
# Purpose: DEPRECATED - forwards to combined HTML report
# Version: 3.1.0 (deprecated)
# Date: 2026-03-12
#
# The standalone HTML simulator has been merged into the combined HTML report.
# This wrapper exists for backward compatibility and forwards all calls to
# generate_conjoint_html_report().
#
# ==============================================================================

# Null coalesce
if (!exists("%||%", mode = "function")) {
  `%||%` <- function(x, y) if (is.null(x)) y else x
}

#' Generate Conjoint HTML Simulator (DEPRECATED)
#'
#' This function is deprecated. The simulator is now embedded within the
#' combined HTML report generated by \code{generate_conjoint_html_report()}.
#'
#' This wrapper forwards to \code{generate_conjoint_html_report()} for
#' backward compatibility. New code should call the report function directly.
#'
#' @param utilities Data frame with Attribute, Level, Utility
#' @param importance Data frame with Attribute, Importance
#' @param model_result Optional turas_conjoint_model
#' @param config Configuration object
#' @param output_path File path for HTML output
#' @return TRS status list
#' @export
generate_conjoint_html_simulator <- function(utilities, importance,
                                              model_result = NULL, config,
                                              output_path) {

  message("[DEPRECATED] generate_conjoint_html_simulator() is deprecated. ",
          "The simulator is now part of the combined HTML report. ",
          "Use generate_conjoint_html_report() instead.")

  # Forward to combined report if available

  if (exists("generate_conjoint_html_report", mode = "function")) {
    conjoint_results <- list(
      utilities    = utilities,
      importance   = importance,
      model_result = model_result,
      diagnostics  = model_result$diagnostics %||% list(),
      config       = config
    )

    report_config <- list(
      brand_colour  = config$brand_colour %||% "#1e40af",
      accent_colour = config$accent_colour %||% "#f59e0b",
      project_name  = config$project_name %||% "Conjoint Simulator"
    )

    return(generate_conjoint_html_report(conjoint_results, output_path, report_config))
  }

  # Fallback if report module not loaded
  list(
    status   = "REFUSED",
    code     = "CONJ_SIMULATOR_DEPRECATED",
    message  = "Standalone simulator is deprecated. Load the html_report module first.",
    how_to_fix = "Source 99_html_report_main.R before calling this function."
  )
}


message("TURAS>Conjoint HTML Simulator wrapper loaded (v3.1.0 - DEPRECATED)")
