# ==============================================================================
# MAXDIFF HTML REPORT - PAGE BUILDER - TURAS V11.0
# ==============================================================================
# Assembles the full HTML document from tables, charts, and data
# Layer 4 of the 4-layer HTML report pipeline
# ==============================================================================

htmlEscape <- function(x) {
  x <- as.character(x)
  x <- gsub("&", "&amp;", x, fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  x <- gsub(">", "&gt;", x, fixed = TRUE)
  x <- gsub('"', "&quot;", x, fixed = TRUE)
  x
}

`%||%` <- function(a, b) if (is.null(a) || length(a) == 0) b else a


# ==============================================================================
# MAIN PAGE BUILDER
# ==============================================================================

#' Build complete MaxDiff HTML report page
#'
#' @param html_data Structured data from transform_maxdiff_for_html()
#' @param tables Named list of HTML table strings
#' @param charts Named list of SVG chart strings
#' @param config Module configuration
#'
#' @return Single HTML string (complete document)
#' @keywords internal
build_maxdiff_page <- function(html_data, tables, charts, config) {

  brand <- html_data$meta$brand_colour %||% "#1e3a5f"
  accent <- html_data$meta$accent_colour %||% "#2aa198"
  project_name <- htmlEscape(html_data$meta$project_name %||% "MaxDiff Analysis")

  css <- build_md_css(brand, accent)
  meta_tags <- build_md_meta(html_data)

  # Determine which tabs to show
  has_preferences <- !is.null(html_data$preferences$scores)
  has_items <- !is.null(html_data$items$count_data)
  has_segments <- !is.null(html_data$segments)
  has_turf <- !is.null(html_data$turf)
  has_diagnostics <- TRUE  # Always show

  # Build panels
  summary_panel <- build_summary_panel(html_data, tables, charts)
  pref_panel <- if (has_preferences) build_preferences_panel(html_data, tables, charts) else ""
  items_panel <- if (has_items) build_items_panel(html_data, tables, charts) else ""
  segments_panel <- if (has_segments) build_segments_panel(html_data, tables, charts) else ""
  turf_panel <- if (has_turf) build_turf_panel(html_data, tables, charts) else ""
  diag_panel <- build_diagnostics_panel(html_data, tables, charts)

  # Build tab navigation
  tab_buttons <- '<button class="md-tab-btn active" data-tab="summary">Summary</button>'
  if (has_preferences) tab_buttons <- paste0(tab_buttons, '\n<button class="md-tab-btn" data-tab="preferences">Preference Scores</button>')
  if (has_items) tab_buttons <- paste0(tab_buttons, '\n<button class="md-tab-btn" data-tab="items">Item Analysis</button>')
  if (has_turf) tab_buttons <- paste0(tab_buttons, '\n<button class="md-tab-btn" data-tab="turf">Portfolio (TURF)</button>')
  if (has_segments) tab_buttons <- paste0(tab_buttons, '\n<button class="md-tab-btn" data-tab="segments">Segments</button>')
  tab_buttons <- paste0(tab_buttons, '\n<button class="md-tab-btn" data-tab="diagnostics">Diagnostics</button>')

  js <- build_md_js()

  # Assemble page
  sprintf('<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  %s
  <title>%s - MaxDiff Report</title>
  <style>%s</style>
</head>
<body>
  <div class="md-header">
    <h1>%s</h1>
    <div class="md-meta">
      <span>MaxDiff Analysis</span>
      <span>%s</span>
      <span>n = %s</span>
      <span>Generated: %s</span>
    </div>
  </div>
  <div class="md-container">
    <div class="md-tab-nav">%s</div>
    <div class="md-content">
      %s
      %s
      %s
      %s
      %s
      %s
    </div>
  </div>
  <div class="md-footer">Generated by TURAS Analytics Platform &middot; MaxDiff Module v11.0 &middot; %s</div>
  <script>%s</script>
</body>
</html>',
    meta_tags,
    project_name,
    css,
    project_name,
    html_data$meta$method %||% "Analysis",
    html_data$meta$n_total %||% "0",
    html_data$meta$generated %||% "",
    tab_buttons,
    summary_panel,
    pref_panel,
    items_panel,
    turf_panel,
    segments_panel,
    diag_panel,
    format(Sys.Date(), "%B %Y"),
    js
  )
}


# ==============================================================================
# PANEL BUILDERS
# ==============================================================================

build_summary_panel <- function(html_data, tables, charts) {

  s <- html_data$summary

  # KPI cards
  metrics <- sprintf(
    '<div class="md-metrics">
      <div class="md-metric-card">
        <div class="md-metric-value">%s</div>
        <div class="md-metric-label">Respondents</div>
      </div>
      <div class="md-metric-card">
        <div class="md-metric-value">%s</div>
        <div class="md-metric-label">Items Tested</div>
      </div>
      <div class="md-metric-card">
        <div class="md-metric-value">%s</div>
        <div class="md-metric-label">Method</div>
      </div>
      <div class="md-metric-card">
        <div class="md-metric-value" style="font-size:15px">%s</div>
        <div class="md-metric-label">Top Item</div>
      </div>
    </div>',
    s$n_total %||% "0",
    s$n_items %||% "0",
    htmlEscape(s$method_label %||% ""),
    htmlEscape(s$top_item %||% "N/A")
  )

  # Summary chart (preference shares)
  chart_html <- ""
  if (!is.null(charts$preference_chart)) {
    chart_html <- sprintf(
      '<div class="md-chart-container"><div class="md-chart-title">Preference Shares</div>%s</div>',
      charts$preference_chart
    )
  }

  sprintf(
    '<div class="md-panel active" id="panel-summary">
      <div class="md-section">
        <h2>Overview</h2>
        %s
        %s
        %s
      </div>
    </div>',
    metrics, s$callout %||% "", chart_html
  )
}


build_preferences_panel <- function(html_data, tables, charts) {

  callout <- html_data$preferences$callout %||% ""
  pref_table <- tables$preference_scores %||% ""
  pref_chart <- ""
  if (!is.null(charts$preference_detail_chart)) {
    pref_chart <- sprintf(
      '<div class="md-chart-container"><div class="md-chart-title">Utility Scores (0-100 Scale)</div>%s</div>',
      charts$preference_detail_chart
    )
  }

  sprintf(
    '<div class="md-panel" id="panel-preferences">
      <div class="md-section">
        <h2>Preference Scores</h2>
        %s
        %s
        %s
      </div>
    </div>',
    callout, pref_chart, pref_table
  )
}


build_items_panel <- function(html_data, tables, charts) {

  callout <- html_data$items$callout %||% ""
  count_table <- tables$count_scores %||% ""
  diverging_chart <- ""
  if (!is.null(charts$diverging_chart)) {
    diverging_chart <- sprintf(
      '<div class="md-chart-container"><div class="md-chart-title">Best vs Worst Selection Frequency</div>%s</div>',
      charts$diverging_chart
    )
  }

  sprintf(
    '<div class="md-panel" id="panel-items">
      <div class="md-section">
        <h2>Item Analysis</h2>
        %s
        %s
        <h3>Detailed Count Scores</h3>
        %s
      </div>
    </div>',
    callout, diverging_chart, count_table
  )
}


build_turf_panel <- function(html_data, tables, charts) {

  callout <- html_data$turf$callout %||% ""
  turf_table <- tables$turf %||% ""
  turf_chart <- ""
  if (!is.null(charts$turf_chart)) {
    turf_chart <- sprintf(
      '<div class="md-chart-container"><div class="md-chart-title">Incremental Reach Curve</div>%s</div>',
      charts$turf_chart
    )
  }

  sprintf(
    '<div class="md-panel" id="panel-turf">
      <div class="md-section">
        <h2>Portfolio Optimization (TURF)</h2>
        %s
        %s
        <h3>Greedy Selection Order</h3>
        %s
      </div>
    </div>',
    callout, turf_chart, turf_table
  )
}


build_segments_panel <- function(html_data, tables, charts) {

  callout <- html_data$segments$callout %||% ""
  seg_table <- tables$segments %||% ""

  sprintf(
    '<div class="md-panel" id="panel-segments">
      <div class="md-section">
        <h2>Segment Analysis</h2>
        %s
        %s
      </div>
    </div>',
    callout, seg_table
  )
}


build_diagnostics_panel <- function(html_data, tables, charts) {

  callout <- html_data$diagnostics$callout %||% ""
  diag_table <- tables$diagnostics %||% ""

  sprintf(
    '<div class="md-panel" id="panel-diagnostics">
      <div class="md-section">
        <h2>Model Diagnostics</h2>
        %s
        %s
      </div>
    </div>',
    callout, diag_table
  )
}


# ==============================================================================
# TURAS META TAGS
# ==============================================================================

build_md_meta <- function(html_data) {
  m <- html_data$meta
  s <- html_data$summary
  tags <- c(
    '<meta name="turas-report-type" content="maxdiff">',
    sprintf('<meta name="turas-generated" content="%s">', m$generated %||% ""),
    sprintf('<meta name="turas-total-n" content="%s">', m$n_total %||% ""),
    sprintf('<meta name="turas-estimation-method" content="%s">', m$method %||% ""),
    sprintf('<meta name="turas-items" content="%s">', m$n_items %||% ""),
    sprintf('<meta name="turas-top-item" content="%s">', htmlEscape(s$top_item %||% "")),
    sprintf('<meta name="turas-source-filename" content="%s">', htmlEscape(m$project_name %||% ""))
  )
  paste(tags, collapse = "\n  ")
}


# ==============================================================================
# CSS
# ==============================================================================

build_md_css <- function(brand, accent) {
  css <- ':root {
  --md-brand: BRAND_TOKEN;
  --md-accent: ACCENT_TOKEN;
  --md-text-primary: #1e293b;
  --md-text-secondary: #64748b;
  --md-bg-surface: #ffffff;
  --md-bg-muted: #f8f9fa;
  --md-border: #e2e8f0;
}
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #f1f5f9; color: var(--md-text-primary); line-height: 1.5; font-size: 14px; }

.md-header { background: var(--md-brand); color: white; padding: 20px 28px; }
.md-header h1 { font-size: 20px; font-weight: 600; margin-bottom: 4px; }
.md-meta { display: flex; gap: 16px; font-size: 12px; opacity: 0.85; flex-wrap: wrap; }

.md-container { max-width: 900px; margin: 0 auto; padding: 0 16px; }
.md-tab-nav { display: flex; gap: 0; background: var(--md-bg-surface); border-bottom: 1px solid var(--md-border); border-radius: 8px 8px 0 0; overflow-x: auto; margin-top: 20px; }
.md-tab-btn { background: transparent; border: none; padding: 10px 16px; font-size: 13px; font-weight: 500; color: var(--md-text-secondary); cursor: pointer; border-bottom: 2px solid transparent; white-space: nowrap; transition: color 0.15s; }
.md-tab-btn:hover { color: var(--md-text-primary); }
.md-tab-btn.active { color: var(--md-brand); border-bottom-color: var(--md-brand); }

.md-content { background: var(--md-bg-surface); border-radius: 0 0 8px 8px; padding: 24px 28px; min-height: 300px; }
.md-panel { display: none; }
.md-panel.active { display: block; }

.md-section { margin-bottom: 28px; }
.md-section h2 { font-size: 17px; font-weight: 600; color: var(--md-brand); margin-bottom: 12px; padding-bottom: 6px; border-bottom: 1px solid var(--md-border); }
.md-section h3 { font-size: 14px; font-weight: 600; color: var(--md-text-primary); margin: 16px 0 8px; }

.md-metrics { display: flex; gap: 12px; margin-bottom: 16px; flex-wrap: wrap; }
.md-metric-card { flex: 1; min-width: 120px; background: var(--md-bg-muted); border-radius: 8px; padding: 14px 12px; text-align: center; }
.md-metric-value { font-size: 20px; font-weight: 700; color: var(--md-brand); }
.md-metric-label { font-size: 11px; color: var(--md-text-secondary); margin-top: 2px; text-transform: uppercase; letter-spacing: 0.3px; }

.md-chart-container { background: var(--md-bg-muted); border-radius: 8px; padding: 12px; margin: 12px 0; }
.md-chart-title { font-size: 13px; font-weight: 600; color: var(--md-text-secondary); text-align: center; margin-bottom: 8px; }

/* Tables */
.md-table { width: 100%; border-collapse: collapse; font-size: 13px; margin: 8px 0; }
.md-table-compact { font-size: 12px; }
.md-th { background: var(--md-bg-muted); padding: 8px 12px; text-align: left; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.4px; color: var(--md-text-secondary); border-bottom: 2px solid var(--md-border); }
.md-th.md-num { text-align: right; }
.md-th.md-label-col { text-align: left; }
.md-td { padding: 7px 12px; border-bottom: 1px solid var(--md-border); vertical-align: middle; }
.md-td.md-num { text-align: right; font-variant-numeric: tabular-nums; }
.md-td.md-label-col { font-weight: 500; }
.md-tr-section td { background: var(--md-bg-muted); font-weight: 600; padding-top: 12px; border-bottom: 1px solid var(--md-border); }

/* Bar in cell */
.md-bar-cell { position: relative; min-height: 22px; display: flex; align-items: center; }
.md-bar-bg { position: absolute; left: 0; top: 0; height: 100%; background: var(--md-brand); opacity: 0.10; border-radius: 3px; }
.md-bar-label { position: relative; z-index: 1; padding-left: 4px; }

/* Badges */
.md-badge-good { display: inline-block; background: #dcfce7; color: #166534; padding: 2px 8px; border-radius: 10px; font-size: 11px; font-weight: 500; }
.md-badge-warn { display: inline-block; background: #fef3c7; color: #92400e; padding: 2px 8px; border-radius: 10px; font-size: 11px; font-weight: 500; }
.md-badge-poor { display: inline-block; background: #fee2e2; color: #991b1b; padding: 2px 8px; border-radius: 10px; font-size: 11px; font-weight: 500; }

/* Callouts */
.md-callout { padding: 12px 16px; border-radius: 6px; margin: 12px 0; font-size: 13px; line-height: 1.5; }
.md-callout-result { background: #eff6ff; border-left: 4px solid #3b82f6; }
.md-callout-method { background: #f8fafc; border-left: 4px solid #94a3b8; }
.md-callout-sampling { background: #fffbeb; border-left: 4px solid #f59e0b; }

.md-positive { color: #16a34a; }
.md-negative { color: #dc2626; }
.md-empty { color: var(--md-text-secondary); font-style: italic; padding: 12px 0; }

.md-footer { text-align: center; padding: 20px; font-size: 11px; color: var(--md-text-secondary); }

/* Print */
@media print {
  .md-tab-nav { display: none; }
  .md-panel { display: block !important; page-break-inside: avoid; }
  .md-header { background: white !important; color: var(--md-brand) !important; border-bottom: 2px solid var(--md-brand); }
  body { background: white; }
}

/* Responsive */
@media (max-width: 600px) {
  .md-content { padding: 16px; }
  .md-metrics { flex-direction: column; }
  .md-tab-btn { padding: 8px 10px; font-size: 12px; }
}'

  css <- gsub("BRAND_TOKEN", brand, css, fixed = TRUE)
  css <- gsub("ACCENT_TOKEN", accent, css, fixed = TRUE)
  css
}


# ==============================================================================
# JAVASCRIPT
# ==============================================================================

build_md_js <- function() {
  '(function() {
  var tabs = document.querySelectorAll(".md-tab-btn");
  var panels = document.querySelectorAll(".md-panel");
  tabs.forEach(function(tab) {
    tab.addEventListener("click", function() {
      var target = this.getAttribute("data-tab");
      tabs.forEach(function(t) { t.classList.remove("active"); });
      panels.forEach(function(p) { p.classList.remove("active"); });
      this.classList.add("active");
      var panel = document.getElementById("panel-" + target);
      if (panel) panel.classList.add("active");
    });
  });
})();'
}
