# ==============================================================================
# Tests for the two dates a brand report carries.
#
# The header badge bar used to end with a bare month and year, taken from
# Sys.Date(). Beside "Wave 1" that read as the wave's date, and on Duncan's
# real IPK report the header said "Wave 1 | September 2026" while the About
# tab said the wave was in field in May. September was the day the file was
# written.
#
# The rule these tests hold: the study's date is its fieldwork period, and a
# generation date has to say that is what it is. Neither is ever guessed.
# fieldwork_dates is free text on the Settings sheet, because a fieldwork
# period is written a dozen different ways and nothing here parses it.
# ==============================================================================
library(testthat)

.find_root_dates <- function() {
  dir <- getwd()
  for (i in 1:10) {
    if (file.exists(file.path(dir, "CLAUDE.md"))) return(dir)
    dir <- dirname(dir)
  }
  getwd()
}
ROOT_DT <- .find_root_dates()
source(file.path(ROOT_DT, "modules", "brand", "R", "01b_section_insights.R"))
source(file.path(ROOT_DT, "modules", "brand", "lib", "html_report",
                 "03_page_builder.R"))

cfg_dt <- function(...) {
  base <- list(client_name = "Test Client", focal_brand = "FOC", wave = 1,
               report_title = "Brand Health Report",
               colour_focal = "#1A5276")
  utils::modifyList(base, list(...))
}

this_month <- format(Sys.Date(), "%B %Y")


test_that("the generation date in the header says it is a generation date", {
  h <- build_br_header(cfg_dt())
  expect_true(grepl(paste0("Generated ", this_month), h, fixed = TRUE))
  # The bare month with no label is what a client read as the study's date.
  expect_false(grepl(paste0("<span>", this_month, "</span>"), h, fixed = TRUE))
  expect_true(grepl("data-br-generated", h, fixed = TRUE))
})


test_that("a study with no fieldwork_dates gets no invented one", {
  h <- build_br_header(cfg_dt())
  expect_false(grepl("Fieldwork", h, fixed = TRUE))
  expect_false(grepl("data-br-fieldwork", h, fixed = TRUE))
  # And the wave badge is still there, so the header did not lose anything.
  expect_true(grepl("<span>Wave 1</span>", h, fixed = TRUE))
})


test_that("fieldwork_dates reaches the header, labelled, ahead of the clock", {
  h <- build_br_header(cfg_dt(fieldwork_dates = "19 to 26 May 2026"))
  expect_true(grepl("Fieldwork: 19 to 26 May 2026", h, fixed = TRUE))
  expect_true(grepl("data-br-fieldwork", h, fixed = TRUE))
  # The study's own date comes before the date the file was written.
  expect_lt(regexpr("data-br-fieldwork", h, fixed = TRUE)[[1]],
            regexpr("data-br-generated", h, fixed = TRUE)[[1]])
  # Both dates are on the page and each one says which it is, so neither can
  # be read as the other.
  expect_true(grepl(paste0("Generated ", this_month), h, fixed = TRUE))
})


test_that("the header takes the analyst's words and does not parse them", {
  for (txt in c("19 to 26 May 2026", "May 2026", "Q2 2026",
                "19/05/2026 to 26/05/2026", "May and June 2026")) {
    h <- build_br_header(cfg_dt(fieldwork_dates = txt))
    expect_true(grepl(paste0("Fieldwork: ", txt), h, fixed = TRUE),
                info = txt)
  }
})


test_that("a blank or whitespace fieldwork_dates is treated as absent", {
  for (v in list("", "   ", NA, NA_character_, NULL, character(0))) {
    h <- build_br_header(cfg_dt(fieldwork_dates = v))
    expect_false(grepl("data-br-fieldwork", h, fixed = TRUE))
    expect_true(grepl("data-br-generated", h, fixed = TRUE))
  }
})


test_that("the About tab states the same fieldwork period as the header", {
  a <- build_br_about_panel(cfg_dt(fieldwork_dates = "19 to 26 May 2026"))
  expect_true(grepl("data-br-about-fieldwork", a, fixed = TRUE))
  expect_true(grepl("Wave 1 fieldwork ran 19 to 26 May 2026", a, fixed = TRUE))
  h <- build_br_header(cfg_dt(fieldwork_dates = "19 to 26 May 2026"))
  # One string, two places. A reader comparing the header with the About tab
  # must not find two different renderings of one period.
  expect_true(grepl("19 to 26 May 2026", h, fixed = TRUE))
})


test_that("About says its own timestamp is when the file was written", {
  a <- build_br_about_panel(cfg_dt())
  expect_true(grepl("Report generated by TURAS Analytics Platform", a,
                    fixed = TRUE))
  expect_true(grepl("not when the study was in field", a, fixed = TRUE))
  expect_false(grepl("data-br-about-fieldwork", a, fixed = TRUE))
})


test_that("fieldwork_dates is a documented Settings key", {
  source(file.path(ROOT_DT, "modules", "brand", "R",
                   "generate_config_templates.R"))
  spec <- .build_brand_settings_def()
  study <- Filter(function(s) identical(s$section_name,
                                        "STUDY IDENTIFICATION"), spec)
  expect_equal(length(study), 1L)
  names_in <- vapply(study[[1]]$fields, function(f) f$name, character(1))
  expect_true("fieldwork_dates" %in% names_in)
  fw <- Filter(function(f) identical(f$name, "fieldwork_dates"),
               study[[1]]$fields)[[1]]
  expect_false(isTRUE(fw$required))
  expect_true(nzchar(fw$description))
})


test_that("no em dash reaches the reader in either date line", {
  a <- build_br_about_panel(cfg_dt(fieldwork_dates = "19 to 26 May 2026"))
  h <- build_br_header(cfg_dt(fieldwork_dates = "19 to 26 May 2026"))
  expect_false(grepl("—", h, fixed = TRUE))
  expect_false(grepl("—", a, fixed = TRUE))
})
